apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb-main
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: $DOCKER_INFLUXDB_INIT_ORG
      defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN